name: continuous-integration

on:
  push:
    branches:
     - "*"
     - "!main"
  pull_request:
    branches: [main]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    env:
      SKIP_PREFLIGHT_CHECK: true
    steps:
      - uses: actions/checkout@v2
      - name: Prepare repository
        run: git fetch --unshallow --tags
      - name: run continuous-integration
        run: |
          yarn install
          yarn test
      - name: cleanup
        run: rm .env